"""
Blind Corner Alert System — Vehicle Detection Pipeline
========================================================
Pi 5 side software: reads video (CP Plus camera stream or a video file),
runs YOLO11 detection with ByteTrack, and raises an ALERT when a tracked
person/vehicle/cyclist is moving inside the configured ROI (if any) — which
would be sent to the Arduino Nano over serial to fire the relay.

Usage:
    python3 detect.py --source dummy_corner.mp4 --out annotated_output.mp4
    python3 detect.py --source rtsp://<cp-plus-camera-ip>/stream1   # live camera
    python3 detect.py --source 0                                    # USB webcam

Requires: ultralytics, opencv-python, torch, lap (for ByteTrack)
    pip install -U ultralytics opencv-python lap

Tracker config: expects custom_bytetrack.yaml in the same folder — a copy of
ultralytics' default bytetrack.yaml with fuse_score explicitly set to True.

ROI (optional): if roi_points.json (generated by set_roi.py) is present next
to this script, only detections inside that polygon trigger an alert. Without
it, ANY detection anywhere in frame triggers STOP — fine for a tightly framed
camera, but for a wide-angle CCTV view you almost certainly want an ROI, or
you'll alert on traffic that has nothing to do with the blind corner.
"""

import argparse
import json
import math
import os
import time
from collections import deque
from dataclasses import dataclass, field

import cv2
import numpy as np
from ultralytics import YOLO

# ----------------------------------------------------------------------------
# Config
# ----------------------------------------------------------------------------

# COCO class ids for everything we want to alert on (from the pretrained YOLO11 model).
# Expanded from vehicles-only: a blind-corner alert also needs pedestrians and
# cyclists, since those are exactly as invisible to a reversing driver.
#
# NOTE on coverage — this is the pretrained COCO class set, it does NOT have
# separate classes for everything you might see on an Indian street:
#   - "scooty" / scooters / mopeds -> fall under class 3 "motorcycle" (COCO
#     doesn't distinguish scooter vs motorcycle body styles, both map here)
#   - auto-rickshaws / tuk-tuks -> NO dedicated COCO class exists. The stock
#     model will inconsistently call these "car", sometimes "motorcycle", and
#     will sometimes miss them entirely, especially from the side. Reliable
#     auto-rickshaw detection needs a model fine-tuned on Indian road data
#     (e.g. the IDD — India Driving Dataset — which has an explicit
#     "autorickshaw" class) rather than stock yolo11n/COCO weights.
ALERT_CLASSES = {0: "person", 1: "bicycle", 2: "car", 3: "motorcycle", 5: "bus", 7: "truck"}

MOVEMENT_THRESHOLD_PX = 8       # minimum centroid displacement (pixels) over the history window
                                 # required to classify a tracked object as moving
HISTORY_LEN = 8                 # compare centroid against ~this many frames ago instead of just the
                                 # previous frame, so slow-but-continuous motion accumulates enough
                                 # displacement to register as MOVING instead of flickering
CONF_THRESHOLD = 0.25           # lowered from 0.35 — pedestrians/two-wheelers are smaller, harder
                                 # targets than cars; the ROI + hold-frame debounce absorb the extra
                                 # noise from the lower threshold
ALERT_HOLD_FRAMES = 15          # retained for API compatibility; movement mode clears immediately
TRACKER_CFG = "custom_bytetrack.yaml"  # local file (copy of ultralytics' bytetrack.yaml with fuse_score fix) — must sit next to this script
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
ROI_FILE = "roi_points.json"    # optional — generated by set_roi.py; if absent, no ROI filtering is applied


class SafetyState:
    SAFE = "SAFE"
    STOP = "STOP"  # alert active -> relay/LED on


# ----------------------------------------------------------------------------
# ROI helpers (same as set_roi.py / run_on_my_video.py)
# ----------------------------------------------------------------------------
def load_roi_polygon(roi_file):
    """Load ROI polygon from JSON file. Returns numpy array of points or None."""
    if not os.path.exists(roi_file):
        print(f"⚠️  No ROI file found ({roi_file}) — running WITHOUT ROI filter, "
              f"every detection in frame will count. Run set_roi.py to scope this to your blind corner.\n")
        return None

    with open(roi_file, 'r') as f:
        data = json.load(f)

    points = data.get("roi_polygon", [])
    if len(points) < 3:
        print(f"⚠️  ROI polygon in {roi_file} has fewer than 3 points — ignoring.")
        return None

    polygon = np.array(points, dtype=np.int32)
    print(f"✅ ROI polygon loaded from {roi_file} ({len(points)} vertices)")
    return polygon


def point_in_polygon(cx, cy, polygon):
    """Check if a point (cx, cy) is inside the polygon using OpenCV."""
    result = cv2.pointPolygonTest(polygon.astype(np.float32), (float(cx), float(cy)), False)
    return result >= 0  # >= 0 means inside or on edge


# ----------------------------------------------------------------------------
# Serial relay stub — mirrors the report's SerialRelayController.
# On the real Pi 5 + Arduino Nano setup, swap this for pyserial writes to
# /dev/ttyACM0 (Arduino Nano over USB).
# ----------------------------------------------------------------------------
class RelayController:
    def __init__(self, port=None, enabled=False):
        self.enabled = enabled
        self.port = port
        self._serial = None
        if enabled:
            try:
                import serial  # pyserial
                self._serial = serial.Serial(port, 9600, timeout=1)
                print(f"[Relay] Connected to Arduino on {port}")
            except Exception as e:
                print(f"[Relay] Could not open {port} ({e}) — running in simulation mode")
                self.enabled = False

    def set_state(self, state: str):
        if self.enabled and self._serial:
            self._serial.write(b"1\n" if state == SafetyState.STOP else b"0\n")
        # simulation / logging mode always prints so you can see it working
        # without hardware attached
        print(f"[Relay] -> {state}", end="\r")


# ----------------------------------------------------------------------------
# Pipeline
# ----------------------------------------------------------------------------
def _local_path(name):
    """Resolve a config file that sits next to this script, so the tracker config is
    found even when the program is launched from a different working directory."""
    candidate = os.path.join(BASE_DIR, name)
    return candidate if os.path.exists(candidate) else name


@dataclass
class FrameResult:
    """What SafetyPipeline.process() reports for one frame."""
    state: str                 # SafetyState.SAFE / SafetyState.STOP
    frame_idx: int             # 1-based index of this frame within the session
    new_alert: bool            # True only on the SAFE -> STOP transition
    num_detected: int = 0      # alert-class objects anywhere in the frame
    num_in_roi: int = 0        # alert-class objects that count toward the alert
    roi_track_ids: list = field(default_factory=list)  # ByteTrack IDs of those objects


class SafetyPipeline:
    """YOLO11 + ByteTrack detection, ROI filtering and SAFE/STOP decision for ONE frame at a time.

    This is the per-frame logic that used to live inline in run(). It is shared by
    the video/file mode (run() below) and the live webcam mode (live_webcam.py), so
    both behave identically. One instance keeps its tracker state, per-track history
    and alert hold-timer for the whole session -- create it once, call process()
    for every frame.

    process() draws the per-object boxes/labels onto `frame` in place. The status
    banner / ROI outline are left to the caller.
    """

    def __init__(self, model, roi_polygon=None, conf=CONF_THRESHOLD, tracker_cfg=None,
                 hold_frames=ALERT_HOLD_FRAMES, imgsz=None, device=None):
        self.model = model
        self.roi_polygon = roi_polygon
        self.use_roi = roi_polygon is not None
        self.conf = conf
        self.tracker_cfg = tracker_cfg or _local_path(TRACKER_CFG)
        self.hold_frames = hold_frames
        self.track_kwargs = {}
        if imgsz:
            self.track_kwargs["imgsz"] = imgsz
        if device:
            self.track_kwargs["device"] = device

        # ByteTrack gives us persistent IDs across frames. For each track we keep
        # a short rolling history of centroids (deque(maxlen=HISTORY_LEN)) instead
        # of just the last position, so the "MOVING"/"static" label is judged over
        # several frames of displacement rather than one noisy frame-to-frame diff.
        self.track_history: dict = {}
        self.hold_timer = 0
        self.state = SafetyState.SAFE
        self.frame_idx = 0

    def process(self, frame) -> FrameResult:
        self.frame_idx += 1

        # persist=True keeps ByteTrack's internal track state alive between
        # calls on this same `model` instance -- that's what makes IDs stable
        # across frames instead of resetting every call.
        results = self.model.track(
            frame,
            persist=True,
            tracker=self.tracker_cfg,
            verbose=False,
            conf=self.conf,
            **self.track_kwargs,
        )[0]

        # SAFE/STOP is based on MOVEMENT inside the ROI, not mere presence.
        any_object_moving = False
        num_detected = 0
        roi_track_ids = []
        num_in_roi = 0
        boxes = results.boxes
        ids = boxes.id.int().cpu().tolist() if boxes.id is not None else [None] * len(boxes)

        for box, tid in zip(boxes, ids):
            cls_id = int(box.cls[0])
            if cls_id not in ALERT_CLASSES:
                continue
            num_detected += 1
            x1, y1, x2, y2 = map(int, box.xyxy[0])
            conf = float(box.conf[0])
            cx, cy = (x1 + x2) / 2, (y1 + y2) / 2

            if self.use_roi and not point_in_polygon(cx, cy, self.roi_polygon):
                cv2.rectangle(frame, (x1, y1), (x2, y2), (128, 128, 128), 1)
                cv2.putText(frame, "outside ROI", (x1, max(20, y1 - 8)),
                            cv2.FONT_HERSHEY_SIMPLEX, 0.4, (128, 128, 128), 1)
                continue

            num_in_roi += 1
            if tid is not None:
                roi_track_ids.append(tid)

            # Compare the current center with the center from HISTORY_LEN
            # observations ago. This reduces jitter and catches slow movement.
            moving = False
            if tid is not None:
                hist = self.track_history.setdefault(tid, deque(maxlen=HISTORY_LEN))
                if len(hist) >= HISTORY_LEN:
                    px, py = hist[0]
                    moving = math.hypot(cx - px, cy - py) > MOVEMENT_THRESHOLD_PX
                hist.append((cx, cy))

            if moving:
                any_object_moving = True

            id_label = f"id{tid}" if tid is not None else "id?"
            label = f"{ALERT_CLASSES[cls_id]} {id_label} {conf:.2f} {'MOVING' if moving else 'static'}"
            color = (0, 0, 255) if moving else (0, 200, 0)
            cv2.rectangle(frame, (x1, y1), (x2, y2), color, 2)
            cv2.putText(frame, label, (x1, max(20, y1 - 8)),
                        cv2.FONT_HERSHEY_SIMPLEX, 0.5, color, 2)

        # Drop stale entries for tracks ByteTrack has already dropped.
        active_ids = {tid for tid in ids if tid is not None}
        self.track_history = {
            tid: hist for tid, hist in self.track_history.items()
            if tid in active_ids
        }

        # No object or a stationary object in the ROI = SAFE.
        # At least one moving object in the ROI = STOP.
        prev_state = self.state
        self.state = SafetyState.STOP if any_object_moving else SafetyState.SAFE
        self.hold_timer = 0

        # Only report a new alert on the SAFE -> STOP transition, not just
        # because time has elapsed since the last one -- an elapsed-time
        # check re-fires repeatedly during one continuous STOP period, inflating
        # the event count.
        new_alert = self.state == SafetyState.STOP and prev_state == SafetyState.SAFE

        return FrameResult(state=self.state, frame_idx=self.frame_idx, new_alert=new_alert,
                           num_detected=num_detected, num_in_roi=num_in_roi,
                           roi_track_ids=roi_track_ids)


def run(source, out_path, model_name="yolo11n.pt", relay_port=None, use_relay=False, show=False):
    print("Loading YOLO11 model...")
    model = YOLO(model_name)

    cap = cv2.VideoCapture(int(source) if str(source).isdigit() else source)
    if not cap.isOpened():
        raise RuntimeError(f"Could not open video source: {source}")

    fps = cap.get(cv2.CAP_PROP_FPS) or 20
    w = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
    h = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))

    roi_polygon = load_roi_polygon(ROI_FILE)

    writer = None
    if out_path:
        writer = cv2.VideoWriter(out_path, cv2.VideoWriter_fourcc(*"mp4v"), fps, (w, h))

    relay = RelayController(port=relay_port, enabled=use_relay)
    pipeline = SafetyPipeline(model, roi_polygon)
    frame_idx = 0
    alert_events = []

    t0 = time.time()
    while True:
        ok, frame = cap.read()
        if not ok:
            break

        result = pipeline.process(frame)
        frame_idx = result.frame_idx
        state = result.state
        if result.new_alert:
            alert_events.append(frame_idx)

        relay.set_state(state)

        # overlay status banner
        banner_color = (0, 0, 255) if state == SafetyState.STOP else (0, 180, 0)
        cv2.rectangle(frame, (0, 0), (260, 40), banner_color, -1)
        cv2.putText(frame, f"STATUS: {state}", (10, 27),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.7, (255, 255, 255), 2)

        if writer:
            writer.write(frame)
        if show:
            cv2.imshow("Blind Corner Alert - Debug View", frame)
            if cv2.waitKey(1) & 0xFF == ord("q"):
                break

    elapsed = time.time() - t0
    cap.release()
    if writer:
        writer.release()
    if show:
        cv2.destroyAllWindows()

    print(f"\nProcessed {frame_idx} frames in {elapsed:.1f}s ({frame_idx/elapsed:.1f} FPS)")
    print(f"Alert triggered {len(alert_events)} time(s) at frames: {alert_events}")
    if out_path:
        print(f"Annotated video saved to: {out_path}")


def main(argv=None):
    parser = argparse.ArgumentParser(description="Blind Corner Alert - YOLO11 + ByteTrack detection")
    parser.add_argument("--source", default="dummy_corner.mp4",
                         help="Video file path, RTSP URL, or camera index (e.g. 0)")
    parser.add_argument("--out", default="annotated_output.mp4", help="Output annotated video path")
    parser.add_argument("--model", default="yolo11n.pt", help="YOLO11 model weights (nano = fastest, good for Pi)")
    parser.add_argument("--relay-port", default="/dev/ttyACM0", help="Serial port for Arduino Nano")
    parser.add_argument("--use-relay", action="store_true", help="Actually send serial signal to Arduino")
    parser.add_argument("--show", action="store_true", help="Show live debug window (needs display)")
    args = parser.parse_args(argv)

    run(args.source, args.out, args.model, args.relay_port, args.use_relay, args.show)


if __name__ == "__main__":
    main()
