"""
Blind Corner Alert System — Vehicle Detection (Easy Run Version, YOLO11 + ByteTrack)
=====================================================================================
HOW TO USE:
  1. Put your video file in the SAME FOLDER as this script
     (e.g. "my_corner.mp4")
  2. Change VIDEO_PATH below to your file's name
  3. Put custom_bytetrack.yaml in the SAME FOLDER as this script
  4. (Optional) Run set_roi.py first to draw your ROI polygon interactively.
     Or manually edit roi_points.json with your polygon coordinates.
  5. Run:  python3 run_on_my_video.py

That's it — no command-line flags needed. Just edit the CONFIG block below.

NOTE: this uses YOLO11 + ByteTrack, so make sure your packages are up to date:
  pip install -U ultralytics lap
"""

import json
import math
import os
import time
from collections import deque

import cv2
import numpy as np
from ultralytics import YOLO

# ============================================================
# CONFIG — edit these
# ============================================================
VIDEO_PATH = "video/sample_03.mp4"    # <-- put your video's filename here
OUTPUT_PATH = "output_annotated.mp4"  # where the annotated result gets saved
MODEL_NAME = "yolo11n.pt"             # nano model = fastest, good for real-time
CONF_THRESHOLD = 0.25                 # lowered from 0.35 — pedestrians and two-wheelers are smaller/
                                       # harder targets than cars, especially at night or at distance;
                                       # 0.35 was missing valid detections. This trades a bit of precision
                                       # for recall — the ROI + hold-frame debounce below absorb the extra
                                       # noise, so a slightly lower threshold is the right trade here.
OUTPUT_SCALE = 0.5                    # frame is resized by this factor BEFORE inference/drawing/writing —
                                       # this is what actually makes 4K footage fast; it was defined but
                                       # unused before, which is why FPS was so low
TRACKER_CFG = "custom_bytetrack.yaml" # local file — must sit next to this script
SHOW_LIVE_WINDOW = True               # True = pop up a live preview window while running (needs a display)
                                       # set to False for headless/production runs (Pi with no monitor)

# ROI (Region of Interest) polygon file — generated by set_roi.py
# IMPORTANT: draw your ROI on a frame at the SAME scale as OUTPUT_SCALE below,
# or the polygon coordinates won't line up. Easiest fix: run set_roi.py first,
# then set OUTPUT_SCALE here to match what set_roi.py used (both default to
# working on the resized frame — see set_roi.py notes).
ROI_FILE = "roi_points.json"
# ============================================================

# COCO class IDs for all objects we want to detect.
# NOTE on coverage — this is the pretrained COCO class set, it does NOT have
# separate classes for everything you might see on an Indian street:
#   - "scooty" / scooters / mopeds -> fall under class 3 "motorcycle" (COCO
#     doesn't distinguish scooter vs motorcycle body styles, both map here)
#   - auto-rickshaws / tuk-tuks -> NO dedicated COCO class exists. The stock
#     model will inconsistently call these "car", sometimes "motorcycle", and
#     will sometimes miss them entirely, especially from the side. Reliable
#     auto-rickshaw detection needs a model fine-tuned on Indian road data
#     (e.g. the IDD — India Driving Dataset — which has an explicit
#     "autorickshaw" class) rather than stock yolo11n/COCO weights.
DETECT_CLASSES = {
    0: "person",
    1: "bicycle",
    2: "car",
    3: "motorcycle",
    5: "bus",
    6: "train",
    7: "truck",
}

# Was 3px — too tight given SKIP_FRAMES-style gaps and detector jitter on
# parked/static vehicles at high resolution; this caused static cars to
# falsely register as "moving" from frame-to-frame box jitter alone.
MOVEMENT_THRESHOLD_PX = 8

# How many frames back to compare a centroid against, instead of just the
# previous frame. A slow-but-continuous vehicle can displace less than
# MOVEMENT_THRESHOLD_PX between two consecutive frames, so it flickers
# MOVING/static/MOVING/static — comparing against ~5-10 frames ago lets that
# same slow displacement accumulate into something that reliably clears the
# threshold, so the label stays MOVING instead of flickering.
HISTORY_LEN = 8

ALERT_HOLD_FRAMES = 15

SAFE, STOP = "SAFE", "STOP"


def load_roi_polygon(roi_file):
    """Load ROI polygon from JSON file. Returns numpy array of points or None."""
    if not os.path.exists(roi_file):
        print(f"⚠️  No ROI file found ({roi_file}). Run set_roi.py first to draw your ROI.")
        print("   Proceeding WITHOUT ROI filter — all detections will be used.\n")
        return None

    with open(roi_file, 'r') as f:
        data = json.load(f)

    points = data.get("roi_polygon", [])
    if len(points) < 3:
        print(f"⚠️  ROI polygon in {roi_file} has fewer than 3 points — ignoring.")
        return None

    polygon = np.array(points, dtype=np.int32)
    print(f"✅ ROI polygon loaded from {roi_file} ({len(points)} vertices)")
    return polygon


def point_in_polygon(cx, cy, polygon):
    """Check if a point (cx, cy) is inside the polygon using OpenCV."""
    result = cv2.pointPolygonTest(polygon.astype(np.float32), (float(cx), float(cy)), False)
    return result >= 0  # >= 0 means inside or on edge


def draw_roi_overlay(frame, polygon, state):
    """Draw the ROI polygon on the frame with state-dependent styling."""
    overlay = frame.copy()

    if state == SAFE:
        fill_color = (0, 180, 0)
        border_color = (0, 255, 0)
    else:
        fill_color = (0, 0, 200)
        border_color = (0, 0, 255)

    cv2.fillPoly(overlay, [polygon], fill_color)
    cv2.addWeighted(overlay, 0.15, frame, 0.85, 0, frame)
    cv2.polylines(frame, [polygon], isClosed=True, color=border_color, thickness=3)

    return frame


def draw_safe_banner(frame, w):
    """Draw a prominent SAFE caution sign when no objects are in the ROI."""
    cv2.rectangle(frame, (0, 0), (360, 50), (0, 160, 0), -1)
    cv2.putText(frame, "STATUS: SAFE", (10, 35),
                cv2.FONT_HERSHEY_SIMPLEX, 1.0, (255, 255, 255), 2)

    icon_x = w - 80
    cv2.rectangle(frame, (icon_x - 10, 5), (icon_x + 65, 45), (0, 180, 0), -1)
    cv2.putText(frame, "OK", (icon_x + 5, 35),
                cv2.FONT_HERSHEY_SIMPLEX, 0.8, (255, 255, 255), 2)


def draw_stop_banner(frame, w):
    """Draw an ALERT / STOP banner when moving objects are inside the ROI."""
    cv2.rectangle(frame, (0, 0), (360, 50), (0, 0, 220), -1)
    cv2.putText(frame, "STATUS: STOP", (10, 35),
                cv2.FONT_HERSHEY_SIMPLEX, 1.0, (255, 255, 255), 2)

    icon_x = w - 120
    cv2.rectangle(frame, (icon_x - 10, 5), (icon_x + 105, 45), (0, 0, 220), -1)
    cv2.putText(frame, "ALERT!", (icon_x + 5, 35),
                cv2.FONT_HERSHEY_SIMPLEX, 0.8, (0, 255, 255), 2)


def main():
    print(f"Loading YOLO11 model ({MODEL_NAME})...")
    model = YOLO(MODEL_NAME)

    cap = cv2.VideoCapture(VIDEO_PATH)
    if not cap.isOpened():
        print(f"\n❌ Could not open '{VIDEO_PATH}'.")
        print("   Make sure the video file is in the same folder as this script,")
        print("   and that VIDEO_PATH above matches its exact filename.")
        return

    fps = cap.get(cv2.CAP_PROP_FPS) or 20
    orig_w = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
    orig_h = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
    total_frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))

    # This is the actual working resolution now that OUTPUT_SCALE is applied.
    w, h = int(orig_w * OUTPUT_SCALE), int(orig_h * OUTPUT_SCALE)
    print(f"Video loaded: {orig_w}x{orig_h} @ {fps:.1f}fps, {total_frames} frames "
          f"(processing at {w}x{h} after OUTPUT_SCALE={OUTPUT_SCALE})")

    # Load ROI polygon
    roi_polygon = load_roi_polygon(ROI_FILE)
    use_roi = roi_polygon is not None

    writer = cv2.VideoWriter(OUTPUT_PATH, cv2.VideoWriter_fourcc(*"mp4v"), fps, (w, h))

    # ByteTrack gives us persistent IDs across frames. For each track we keep
    # a short rolling history of centroids (deque(maxlen=HISTORY_LEN)) instead
    # of just the last position, so "moving" is judged over several frames of
    # displacement rather than one noisy frame-to-frame diff.
    track_history: dict[int, deque] = {}
    hold_timer = 0
    state = SAFE
    prev_state = SAFE
    frame_idx = 0
    alert_events = []

    t0 = time.time()
    while True:
        ok, frame = cap.read()
        if not ok:
            break
        frame_idx += 1

        # ---- Resize FIRST so every downstream step (inference, ROI check,
        # drawing, writing) works on the smaller frame. This is the fix that
        # actually uses OUTPUT_SCALE — previously it was defined but unused,
        # so the whole pipeline ran on full 4K frames regardless. ----
        if OUTPUT_SCALE != 1.0:
            frame = cv2.resize(frame, (w, h))

        # persist=True keeps ByteTrack's internal track state alive between
        # calls on this same `model` instance — that's what makes IDs stable
        # across frames instead of resetting every call.
        results = model.track(
            frame,
            persist=True,
            tracker=TRACKER_CFG,
            verbose=False,
            conf=CONF_THRESHOLD,
        )[0]

        # `any_object_present` drives the SAFE/STOP decision: for a blind-corner
        # alert, a vehicle/pedestrian/etc. simply BEING in the ROI is the hazard
        # — you don't get to wait a frame or two to confirm it's "moving" before
        # warning the driver. `moving` is kept only as an on-screen label (handy
        # for telling a car that's driving through the zone apart from one that's
        # sitting parked in it), it no longer gates the alert itself.
        any_object_present = False
        boxes = results.boxes
        ids = boxes.id.int().cpu().tolist() if boxes.id is not None else [None] * len(boxes)

        for box, tid in zip(boxes, ids):
            cls_id = int(box.cls[0])
            if cls_id not in DETECT_CLASSES:
                continue
            x1, y1, x2, y2 = map(int, box.xyxy[0])
            conf = float(box.conf[0])
            cx, cy = (x1 + x2) / 2, (y1 + y2) / 2

            # ---- ROI FILTER: only keep detections whose centroid is INSIDE the polygon ----
            if use_roi and not point_in_polygon(cx, cy, roi_polygon):
                cv2.rectangle(frame, (x1, y1), (x2, y2), (128, 128, 128), 1)
                cv2.putText(frame, "outside ROI", (x1, max(20, y1 - 8)),
                            cv2.FONT_HERSHEY_SIMPLEX, 0.4, (128, 128, 128), 1)
                continue

            any_object_present = True  # in the ROI at all -> STOP, regardless of motion

            # Compare against the OLDEST centroid in this track's history
            # window (~HISTORY_LEN frames ago) rather than just the previous
            # frame — slow-but-continuous motion accumulates enough
            # displacement over that window to clear MOVEMENT_THRESHOLD_PX
            # reliably, instead of flickering MOVING/static frame to frame.
            moving = False
            if tid is not None:
                hist = track_history.setdefault(tid, deque(maxlen=HISTORY_LEN))
                if len(hist) == HISTORY_LEN:
                    px, py = hist[0]
                    moving = math.hypot(cx - px, cy - py) > MOVEMENT_THRESHOLD_PX
                hist.append((cx, cy))

            id_label = f"id{tid}" if tid is not None else "id?"
            label = f"{DETECT_CLASSES[cls_id]} {id_label} {conf:.2f} {'MOVING' if moving else 'static'}"
            color = (0, 0, 255) if moving else (0, 200, 0)
            cv2.rectangle(frame, (x1, y1), (x2, y2), color, 2)
            cv2.putText(frame, label, (x1, max(20, y1 - 8)),
                        cv2.FONT_HERSHEY_SIMPLEX, 0.5, color, 2)

        # drop stale entries for tracks that ByteTrack itself has already dropped
        active_ids = {tid for tid in ids if tid is not None}
        track_history = {tid: h for tid, h in track_history.items() if tid in active_ids}

        if any_object_present:
            hold_timer = ALERT_HOLD_FRAMES
            state = STOP
        elif hold_timer > 0:
            hold_timer -= 1
            state = STOP
        else:
            state = SAFE

        # ---- FIXED: only log a new alert event on the SAFE -> STOP
        # transition, not just because some time has elapsed since the last
        # logged event. The old check (frame_idx - alert_events[-1] >
        # ALERT_HOLD_FRAMES) re-fired every ~16 frames during one continuous
        # STOP period, which is why 14 "alerts" were logged for what was
        # likely a single sustained motion event. ----
        if state == STOP and prev_state == SAFE:
            alert_events.append(frame_idx)
        prev_state = state

        # ---- Draw ROI polygon overlay ----
        if use_roi:
            frame = draw_roi_overlay(frame, roi_polygon, state)

        # ---- Draw status banner ----
        if state == SAFE:
            draw_safe_banner(frame, w)
        else:
            draw_stop_banner(frame, w)

        writer.write(frame)
        if SHOW_LIVE_WINDOW:
            cv2.imshow("Blind Corner Alert - Preview", frame)
            if cv2.waitKey(1) & 0xFF == ord("q"):
                break

        if frame_idx % 30 == 0:
            print(f"  processed {frame_idx}/{total_frames} frames...", end="\r")

    elapsed = time.time() - t0
    cap.release()
    writer.release()
    if SHOW_LIVE_WINDOW:
        cv2.destroyAllWindows()

    print(f"\n\n✅ Done! Processed {frame_idx} frames in {elapsed:.1f}s ({frame_idx/elapsed:.1f} FPS)")
    print(f"🚨 Alert triggered {len(alert_events)} time(s), at frames: {alert_events}")
    print(f"📁 Annotated video saved to: {OUTPUT_PATH}")


if __name__ == "__main__":
    main()